/* 
 * OpenBots Server API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using OpenBots.Server.SDK.Client;
using OpenBots.Server.SDK.Model;

namespace OpenBots.Server.SDK.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IOrganizationUnitMembersApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets all the members of an organization unit (department)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">organization identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="filter"> (optional)</param>
        /// <param name="orderby"> (optional)</param>
        /// <param name="top"> (optional, default to 100)</param>
        /// <param name="skip"> (optional, default to 0)</param>
        /// <returns>OrganizationUnitMember</returns>
        OrganizationUnitMember ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersGet (string organizationId, string apiVersion, string filter = null, string orderby = null, int? top = null, int? skip = null);

        /// <summary>
        /// Gets all the members of an organization unit (department)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">organization identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="filter"> (optional)</param>
        /// <param name="orderby"> (optional)</param>
        /// <param name="top"> (optional, default to 100)</param>
        /// <param name="skip"> (optional, default to 0)</param>
        /// <returns>ApiResponse of OrganizationUnitMember</returns>
        ApiResponse<OrganizationUnitMember> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersGetWithHttpInfo (string organizationId, string apiVersion, string filter = null, string orderby = null, int? top = null, int? skip = null);
        /// <summary>
        /// Delete member from an organization unit
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <returns>IActionResult</returns>
        IActionResult ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDelete (string id, string apiVersion, string organizationId);

        /// <summary>
        /// Delete member from an organization unit
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <returns>ApiResponse of IActionResult</returns>
        ApiResponse<IActionResult> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDeleteWithHttpInfo (string id, string apiVersion, string organizationId);
        /// <summary>
        /// Updates the partial details of the organization unit member
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization unit member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <param name="body">Value of the organization unit member to be updated (optional)</param>
        /// <returns>IActionResult</returns>
        IActionResult ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatch (string id, string apiVersion, string organizationId, List<Operation> body = null);

        /// <summary>
        /// Updates the partial details of the organization unit member
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization unit member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <param name="body">Value of the organization unit member to be updated (optional)</param>
        /// <returns>ApiResponse of IActionResult</returns>
        ApiResponse<IActionResult> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatchWithHttpInfo (string id, string apiVersion, string organizationId, List<Operation> body = null);
        /// <summary>
        /// Updates a member of an organization unit
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">Organization identifier</param>
        /// <param name="id">Member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="body">Member value to be updated (optional)</param>
        /// <returns>IActionResult</returns>
        IActionResult ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPut (string organizationId, string id, string apiVersion, OrganizationUnitMember body = null);

        /// <summary>
        /// Updates a member of an organization unit
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">Organization identifier</param>
        /// <param name="id">Member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="body">Member value to be updated (optional)</param>
        /// <returns>ApiResponse of IActionResult</returns>
        ApiResponse<IActionResult> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPutWithHttpInfo (string organizationId, string id, string apiVersion, OrganizationUnitMember body = null);
        /// <summary>
        /// Adds a organization unit member to an organization unit
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">Organization identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="body">Details of the organization unit member (optional)</param>
        /// <returns>OrganizationUnitMember</returns>
        OrganizationUnitMember ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersPost (string organizationId, string apiVersion, OrganizationUnitMember body = null);

        /// <summary>
        /// Adds a organization unit member to an organization unit
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">Organization identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="body">Details of the organization unit member (optional)</param>
        /// <returns>ApiResponse of OrganizationUnitMember</returns>
        ApiResponse<OrganizationUnitMember> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersPostWithHttpInfo (string organizationId, string apiVersion, OrganizationUnitMember body = null);
        /// <summary>
        /// Gets the organization unit member for a particular organization.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization unit member id</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <returns>OrganizationUnitMember</returns>
        OrganizationUnitMember GetOrganizationUnitMember (string id, string apiVersion, string organizationId);

        /// <summary>
        /// Gets the organization unit member for a particular organization.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization unit member id</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <returns>ApiResponse of OrganizationUnitMember</returns>
        ApiResponse<OrganizationUnitMember> GetOrganizationUnitMemberWithHttpInfo (string id, string apiVersion, string organizationId);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Gets all the members of an organization unit (department)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">organization identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="filter"> (optional)</param>
        /// <param name="orderby"> (optional)</param>
        /// <param name="top"> (optional, default to 100)</param>
        /// <param name="skip"> (optional, default to 0)</param>
        /// <returns>Task of OrganizationUnitMember</returns>
        System.Threading.Tasks.Task<OrganizationUnitMember> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersGetAsync (string organizationId, string apiVersion, string filter = null, string orderby = null, int? top = null, int? skip = null);

        /// <summary>
        /// Gets all the members of an organization unit (department)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">organization identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="filter"> (optional)</param>
        /// <param name="orderby"> (optional)</param>
        /// <param name="top"> (optional, default to 100)</param>
        /// <param name="skip"> (optional, default to 0)</param>
        /// <returns>Task of ApiResponse (OrganizationUnitMember)</returns>
        System.Threading.Tasks.Task<ApiResponse<OrganizationUnitMember>> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersGetAsyncWithHttpInfo (string organizationId, string apiVersion, string filter = null, string orderby = null, int? top = null, int? skip = null);
        /// <summary>
        /// Delete member from an organization unit
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <returns>Task of IActionResult</returns>
        System.Threading.Tasks.Task<IActionResult> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDeleteAsync (string id, string apiVersion, string organizationId);

        /// <summary>
        /// Delete member from an organization unit
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <returns>Task of ApiResponse (IActionResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<IActionResult>> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDeleteAsyncWithHttpInfo (string id, string apiVersion, string organizationId);
        /// <summary>
        /// Updates the partial details of the organization unit member
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization unit member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <param name="body">Value of the organization unit member to be updated (optional)</param>
        /// <returns>Task of IActionResult</returns>
        System.Threading.Tasks.Task<IActionResult> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatchAsync (string id, string apiVersion, string organizationId, List<Operation> body = null);

        /// <summary>
        /// Updates the partial details of the organization unit member
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization unit member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <param name="body">Value of the organization unit member to be updated (optional)</param>
        /// <returns>Task of ApiResponse (IActionResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<IActionResult>> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatchAsyncWithHttpInfo (string id, string apiVersion, string organizationId, List<Operation> body = null);
        /// <summary>
        /// Updates a member of an organization unit
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">Organization identifier</param>
        /// <param name="id">Member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="body">Member value to be updated (optional)</param>
        /// <returns>Task of IActionResult</returns>
        System.Threading.Tasks.Task<IActionResult> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPutAsync (string organizationId, string id, string apiVersion, OrganizationUnitMember body = null);

        /// <summary>
        /// Updates a member of an organization unit
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">Organization identifier</param>
        /// <param name="id">Member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="body">Member value to be updated (optional)</param>
        /// <returns>Task of ApiResponse (IActionResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<IActionResult>> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPutAsyncWithHttpInfo (string organizationId, string id, string apiVersion, OrganizationUnitMember body = null);
        /// <summary>
        /// Adds a organization unit member to an organization unit
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">Organization identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="body">Details of the organization unit member (optional)</param>
        /// <returns>Task of OrganizationUnitMember</returns>
        System.Threading.Tasks.Task<OrganizationUnitMember> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersPostAsync (string organizationId, string apiVersion, OrganizationUnitMember body = null);

        /// <summary>
        /// Adds a organization unit member to an organization unit
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">Organization identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="body">Details of the organization unit member (optional)</param>
        /// <returns>Task of ApiResponse (OrganizationUnitMember)</returns>
        System.Threading.Tasks.Task<ApiResponse<OrganizationUnitMember>> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersPostAsyncWithHttpInfo (string organizationId, string apiVersion, OrganizationUnitMember body = null);
        /// <summary>
        /// Gets the organization unit member for a particular organization.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization unit member id</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <returns>Task of OrganizationUnitMember</returns>
        System.Threading.Tasks.Task<OrganizationUnitMember> GetOrganizationUnitMemberAsync (string id, string apiVersion, string organizationId);

        /// <summary>
        /// Gets the organization unit member for a particular organization.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization unit member id</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <returns>Task of ApiResponse (OrganizationUnitMember)</returns>
        System.Threading.Tasks.Task<ApiResponse<OrganizationUnitMember>> GetOrganizationUnitMemberAsyncWithHttpInfo (string id, string apiVersion, string organizationId);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class OrganizationUnitMembersApi : IOrganizationUnitMembersApi
    {
        private OpenBots.Server.SDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationUnitMembersApi"/> class.
        /// </summary>
        /// <returns></returns>
        public OrganizationUnitMembersApi(String basePath)
        {
            this.Configuration = new OpenBots.Server.SDK.Client.Configuration { BasePath = basePath };

            ExceptionFactory = OpenBots.Server.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationUnitMembersApi"/> class
        /// </summary>
        /// <returns></returns>
        public OrganizationUnitMembersApi()
        {
            this.Configuration = OpenBots.Server.SDK.Client.Configuration.Default;

            ExceptionFactory = OpenBots.Server.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationUnitMembersApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public OrganizationUnitMembersApi(OpenBots.Server.SDK.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = OpenBots.Server.SDK.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = OpenBots.Server.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public OpenBots.Server.SDK.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public OpenBots.Server.SDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Gets all the members of an organization unit (department) 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">organization identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="filter"> (optional)</param>
        /// <param name="orderby"> (optional)</param>
        /// <param name="top"> (optional, default to 100)</param>
        /// <param name="skip"> (optional, default to 0)</param>
        /// <returns>OrganizationUnitMember</returns>
        public OrganizationUnitMember ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersGet (string organizationId, string apiVersion, string filter = null, string orderby = null, int? top = null, int? skip = null)
        {
             ApiResponse<OrganizationUnitMember> localVarResponse = ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersGetWithHttpInfo(organizationId, apiVersion, filter, orderby, top, skip);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets all the members of an organization unit (department) 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">organization identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="filter"> (optional)</param>
        /// <param name="orderby"> (optional)</param>
        /// <param name="top"> (optional, default to 100)</param>
        /// <param name="skip"> (optional, default to 0)</param>
        /// <returns>ApiResponse of OrganizationUnitMember</returns>
        public ApiResponse< OrganizationUnitMember > ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersGetWithHttpInfo (string organizationId, string apiVersion, string filter = null, string orderby = null, int? top = null, int? skip = null)
        {
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersGet");
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new ApiException(400, "Missing required parameter 'apiVersion' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersGet");

            var localVarPath = "/api/v{apiVersion}/Organizations/{organizationId}/OrganizationUnitMembers";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (organizationId != null) localVarPathParams.Add("organizationId", this.Configuration.ApiClient.ParameterToString(organizationId)); // path parameter
            if (apiVersion != null) localVarPathParams.Add("apiVersion", this.Configuration.ApiClient.ParameterToString(apiVersion)); // path parameter
            if (filter != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "$filter", filter)); // query parameter
            if (orderby != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "$orderby", orderby)); // query parameter
            if (top != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "$top", top)); // query parameter
            if (skip != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "$skip", skip)); // query parameter
            // authentication (oauth2) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OrganizationUnitMember>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (OrganizationUnitMember) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(OrganizationUnitMember)));
        }

        /// <summary>
        /// Gets all the members of an organization unit (department) 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">organization identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="filter"> (optional)</param>
        /// <param name="orderby"> (optional)</param>
        /// <param name="top"> (optional, default to 100)</param>
        /// <param name="skip"> (optional, default to 0)</param>
        /// <returns>Task of OrganizationUnitMember</returns>
        public async System.Threading.Tasks.Task<OrganizationUnitMember> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersGetAsync (string organizationId, string apiVersion, string filter = null, string orderby = null, int? top = null, int? skip = null)
        {
             ApiResponse<OrganizationUnitMember> localVarResponse = await ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersGetAsyncWithHttpInfo(organizationId, apiVersion, filter, orderby, top, skip);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets all the members of an organization unit (department) 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">organization identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="filter"> (optional)</param>
        /// <param name="orderby"> (optional)</param>
        /// <param name="top"> (optional, default to 100)</param>
        /// <param name="skip"> (optional, default to 0)</param>
        /// <returns>Task of ApiResponse (OrganizationUnitMember)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<OrganizationUnitMember>> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersGetAsyncWithHttpInfo (string organizationId, string apiVersion, string filter = null, string orderby = null, int? top = null, int? skip = null)
        {
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersGet");
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new ApiException(400, "Missing required parameter 'apiVersion' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersGet");

            var localVarPath = "/api/v{apiVersion}/Organizations/{organizationId}/OrganizationUnitMembers";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (organizationId != null) localVarPathParams.Add("organizationId", this.Configuration.ApiClient.ParameterToString(organizationId)); // path parameter
            if (apiVersion != null) localVarPathParams.Add("apiVersion", this.Configuration.ApiClient.ParameterToString(apiVersion)); // path parameter
            if (filter != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "$filter", filter)); // query parameter
            if (orderby != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "$orderby", orderby)); // query parameter
            if (top != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "$top", top)); // query parameter
            if (skip != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "$skip", skip)); // query parameter
            // authentication (oauth2) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OrganizationUnitMember>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (OrganizationUnitMember) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(OrganizationUnitMember)));
        }

        /// <summary>
        /// Delete member from an organization unit 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <returns>IActionResult</returns>
        public IActionResult ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDelete (string id, string apiVersion, string organizationId)
        {
             ApiResponse<IActionResult> localVarResponse = ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDeleteWithHttpInfo(id, apiVersion, organizationId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Delete member from an organization unit 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <returns>ApiResponse of IActionResult</returns>
        public ApiResponse< IActionResult > ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDeleteWithHttpInfo (string id, string apiVersion, string organizationId)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDelete");
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new ApiException(400, "Missing required parameter 'apiVersion' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDelete");
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDelete");

            var localVarPath = "/api/v{apiVersion}/Organizations/{organizationId}/OrganizationUnitMembers/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (apiVersion != null) localVarPathParams.Add("apiVersion", this.Configuration.ApiClient.ParameterToString(apiVersion)); // path parameter
            if (organizationId != null) localVarPathParams.Add("organizationId", this.Configuration.ApiClient.ParameterToString(organizationId)); // path parameter
            // authentication (oauth2) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<IActionResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (IActionResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(IActionResult)));
        }

        /// <summary>
        /// Delete member from an organization unit 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <returns>Task of IActionResult</returns>
        public async System.Threading.Tasks.Task<IActionResult> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDeleteAsync (string id, string apiVersion, string organizationId)
        {
             ApiResponse<IActionResult> localVarResponse = await ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDeleteAsyncWithHttpInfo(id, apiVersion, organizationId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Delete member from an organization unit 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <returns>Task of ApiResponse (IActionResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<IActionResult>> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDeleteAsyncWithHttpInfo (string id, string apiVersion, string organizationId)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDelete");
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new ApiException(400, "Missing required parameter 'apiVersion' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDelete");
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDelete");

            var localVarPath = "/api/v{apiVersion}/Organizations/{organizationId}/OrganizationUnitMembers/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (apiVersion != null) localVarPathParams.Add("apiVersion", this.Configuration.ApiClient.ParameterToString(apiVersion)); // path parameter
            if (organizationId != null) localVarPathParams.Add("organizationId", this.Configuration.ApiClient.ParameterToString(organizationId)); // path parameter
            // authentication (oauth2) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<IActionResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (IActionResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(IActionResult)));
        }

        /// <summary>
        /// Updates the partial details of the organization unit member 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization unit member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <param name="body">Value of the organization unit member to be updated (optional)</param>
        /// <returns>IActionResult</returns>
        public IActionResult ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatch (string id, string apiVersion, string organizationId, List<Operation> body = null)
        {
             ApiResponse<IActionResult> localVarResponse = ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatchWithHttpInfo(id, apiVersion, organizationId, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Updates the partial details of the organization unit member 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization unit member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <param name="body">Value of the organization unit member to be updated (optional)</param>
        /// <returns>ApiResponse of IActionResult</returns>
        public ApiResponse< IActionResult > ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatchWithHttpInfo (string id, string apiVersion, string organizationId, List<Operation> body = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatch");
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new ApiException(400, "Missing required parameter 'apiVersion' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatch");
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatch");

            var localVarPath = "/api/v{apiVersion}/Organizations/{organizationId}/OrganizationUnitMembers/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (apiVersion != null) localVarPathParams.Add("apiVersion", this.Configuration.ApiClient.ParameterToString(apiVersion)); // path parameter
            if (organizationId != null) localVarPathParams.Add("organizationId", this.Configuration.ApiClient.ParameterToString(organizationId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (oauth2) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<IActionResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (IActionResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(IActionResult)));
        }

        /// <summary>
        /// Updates the partial details of the organization unit member 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization unit member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <param name="body">Value of the organization unit member to be updated (optional)</param>
        /// <returns>Task of IActionResult</returns>
        public async System.Threading.Tasks.Task<IActionResult> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatchAsync (string id, string apiVersion, string organizationId, List<Operation> body = null)
        {
             ApiResponse<IActionResult> localVarResponse = await ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatchAsyncWithHttpInfo(id, apiVersion, organizationId, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Updates the partial details of the organization unit member 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization unit member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <param name="body">Value of the organization unit member to be updated (optional)</param>
        /// <returns>Task of ApiResponse (IActionResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<IActionResult>> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatchAsyncWithHttpInfo (string id, string apiVersion, string organizationId, List<Operation> body = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatch");
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new ApiException(400, "Missing required parameter 'apiVersion' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatch");
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatch");

            var localVarPath = "/api/v{apiVersion}/Organizations/{organizationId}/OrganizationUnitMembers/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (apiVersion != null) localVarPathParams.Add("apiVersion", this.Configuration.ApiClient.ParameterToString(apiVersion)); // path parameter
            if (organizationId != null) localVarPathParams.Add("organizationId", this.Configuration.ApiClient.ParameterToString(organizationId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (oauth2) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPatch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<IActionResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (IActionResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(IActionResult)));
        }

        /// <summary>
        /// Updates a member of an organization unit 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">Organization identifier</param>
        /// <param name="id">Member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="body">Member value to be updated (optional)</param>
        /// <returns>IActionResult</returns>
        public IActionResult ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPut (string organizationId, string id, string apiVersion, OrganizationUnitMember body = null)
        {
             ApiResponse<IActionResult> localVarResponse = ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPutWithHttpInfo(organizationId, id, apiVersion, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Updates a member of an organization unit 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">Organization identifier</param>
        /// <param name="id">Member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="body">Member value to be updated (optional)</param>
        /// <returns>ApiResponse of IActionResult</returns>
        public ApiResponse< IActionResult > ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPutWithHttpInfo (string organizationId, string id, string apiVersion, OrganizationUnitMember body = null)
        {
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPut");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPut");
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new ApiException(400, "Missing required parameter 'apiVersion' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPut");

            var localVarPath = "/api/v{apiVersion}/Organizations/{organizationId}/OrganizationUnitMembers/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (organizationId != null) localVarPathParams.Add("organizationId", this.Configuration.ApiClient.ParameterToString(organizationId)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (apiVersion != null) localVarPathParams.Add("apiVersion", this.Configuration.ApiClient.ParameterToString(apiVersion)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (oauth2) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<IActionResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (IActionResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(IActionResult)));
        }

        /// <summary>
        /// Updates a member of an organization unit 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">Organization identifier</param>
        /// <param name="id">Member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="body">Member value to be updated (optional)</param>
        /// <returns>Task of IActionResult</returns>
        public async System.Threading.Tasks.Task<IActionResult> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPutAsync (string organizationId, string id, string apiVersion, OrganizationUnitMember body = null)
        {
             ApiResponse<IActionResult> localVarResponse = await ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPutAsyncWithHttpInfo(organizationId, id, apiVersion, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Updates a member of an organization unit 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">Organization identifier</param>
        /// <param name="id">Member identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="body">Member value to be updated (optional)</param>
        /// <returns>Task of ApiResponse (IActionResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<IActionResult>> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPutAsyncWithHttpInfo (string organizationId, string id, string apiVersion, OrganizationUnitMember body = null)
        {
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPut");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPut");
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new ApiException(400, "Missing required parameter 'apiVersion' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPut");

            var localVarPath = "/api/v{apiVersion}/Organizations/{organizationId}/OrganizationUnitMembers/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (organizationId != null) localVarPathParams.Add("organizationId", this.Configuration.ApiClient.ParameterToString(organizationId)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (apiVersion != null) localVarPathParams.Add("apiVersion", this.Configuration.ApiClient.ParameterToString(apiVersion)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (oauth2) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersIdPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<IActionResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (IActionResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(IActionResult)));
        }

        /// <summary>
        /// Adds a organization unit member to an organization unit 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">Organization identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="body">Details of the organization unit member (optional)</param>
        /// <returns>OrganizationUnitMember</returns>
        public OrganizationUnitMember ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersPost (string organizationId, string apiVersion, OrganizationUnitMember body = null)
        {
             ApiResponse<OrganizationUnitMember> localVarResponse = ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersPostWithHttpInfo(organizationId, apiVersion, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Adds a organization unit member to an organization unit 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">Organization identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="body">Details of the organization unit member (optional)</param>
        /// <returns>ApiResponse of OrganizationUnitMember</returns>
        public ApiResponse< OrganizationUnitMember > ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersPostWithHttpInfo (string organizationId, string apiVersion, OrganizationUnitMember body = null)
        {
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersPost");
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new ApiException(400, "Missing required parameter 'apiVersion' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersPost");

            var localVarPath = "/api/v{apiVersion}/Organizations/{organizationId}/OrganizationUnitMembers";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (organizationId != null) localVarPathParams.Add("organizationId", this.Configuration.ApiClient.ParameterToString(organizationId)); // path parameter
            if (apiVersion != null) localVarPathParams.Add("apiVersion", this.Configuration.ApiClient.ParameterToString(apiVersion)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (oauth2) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OrganizationUnitMember>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (OrganizationUnitMember) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(OrganizationUnitMember)));
        }

        /// <summary>
        /// Adds a organization unit member to an organization unit 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">Organization identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="body">Details of the organization unit member (optional)</param>
        /// <returns>Task of OrganizationUnitMember</returns>
        public async System.Threading.Tasks.Task<OrganizationUnitMember> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersPostAsync (string organizationId, string apiVersion, OrganizationUnitMember body = null)
        {
             ApiResponse<OrganizationUnitMember> localVarResponse = await ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersPostAsyncWithHttpInfo(organizationId, apiVersion, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Adds a organization unit member to an organization unit 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">Organization identifier</param>
        /// <param name="apiVersion"></param>
        /// <param name="body">Details of the organization unit member (optional)</param>
        /// <returns>Task of ApiResponse (OrganizationUnitMember)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<OrganizationUnitMember>> ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersPostAsyncWithHttpInfo (string organizationId, string apiVersion, OrganizationUnitMember body = null)
        {
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersPost");
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new ApiException(400, "Missing required parameter 'apiVersion' when calling OrganizationUnitMembersApi->ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersPost");

            var localVarPath = "/api/v{apiVersion}/Organizations/{organizationId}/OrganizationUnitMembers";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (organizationId != null) localVarPathParams.Add("organizationId", this.Configuration.ApiClient.ParameterToString(organizationId)); // path parameter
            if (apiVersion != null) localVarPathParams.Add("apiVersion", this.Configuration.ApiClient.ParameterToString(apiVersion)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (oauth2) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiVapiVersionOrganizationsOrganizationIdOrganizationUnitMembersPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OrganizationUnitMember>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (OrganizationUnitMember) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(OrganizationUnitMember)));
        }

        /// <summary>
        /// Gets the organization unit member for a particular organization. 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization unit member id</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <returns>OrganizationUnitMember</returns>
        public OrganizationUnitMember GetOrganizationUnitMember (string id, string apiVersion, string organizationId)
        {
             ApiResponse<OrganizationUnitMember> localVarResponse = GetOrganizationUnitMemberWithHttpInfo(id, apiVersion, organizationId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the organization unit member for a particular organization. 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization unit member id</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <returns>ApiResponse of OrganizationUnitMember</returns>
        public ApiResponse< OrganizationUnitMember > GetOrganizationUnitMemberWithHttpInfo (string id, string apiVersion, string organizationId)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling OrganizationUnitMembersApi->GetOrganizationUnitMember");
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new ApiException(400, "Missing required parameter 'apiVersion' when calling OrganizationUnitMembersApi->GetOrganizationUnitMember");
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling OrganizationUnitMembersApi->GetOrganizationUnitMember");

            var localVarPath = "/api/v{apiVersion}/Organizations/{organizationId}/OrganizationUnitMembers/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (apiVersion != null) localVarPathParams.Add("apiVersion", this.Configuration.ApiClient.ParameterToString(apiVersion)); // path parameter
            if (organizationId != null) localVarPathParams.Add("organizationId", this.Configuration.ApiClient.ParameterToString(organizationId)); // path parameter
            // authentication (oauth2) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetOrganizationUnitMember", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OrganizationUnitMember>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (OrganizationUnitMember) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(OrganizationUnitMember)));
        }

        /// <summary>
        /// Gets the organization unit member for a particular organization. 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization unit member id</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <returns>Task of OrganizationUnitMember</returns>
        public async System.Threading.Tasks.Task<OrganizationUnitMember> GetOrganizationUnitMemberAsync (string id, string apiVersion, string organizationId)
        {
             ApiResponse<OrganizationUnitMember> localVarResponse = await GetOrganizationUnitMemberAsyncWithHttpInfo(id, apiVersion, organizationId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets the organization unit member for a particular organization. 
        /// </summary>
        /// <exception cref="OpenBots.Server.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Organization unit member id</param>
        /// <param name="apiVersion"></param>
        /// <param name="organizationId"></param>
        /// <returns>Task of ApiResponse (OrganizationUnitMember)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<OrganizationUnitMember>> GetOrganizationUnitMemberAsyncWithHttpInfo (string id, string apiVersion, string organizationId)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling OrganizationUnitMembersApi->GetOrganizationUnitMember");
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new ApiException(400, "Missing required parameter 'apiVersion' when calling OrganizationUnitMembersApi->GetOrganizationUnitMember");
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling OrganizationUnitMembersApi->GetOrganizationUnitMember");

            var localVarPath = "/api/v{apiVersion}/Organizations/{organizationId}/OrganizationUnitMembers/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (apiVersion != null) localVarPathParams.Add("apiVersion", this.Configuration.ApiClient.ParameterToString(apiVersion)); // path parameter
            if (organizationId != null) localVarPathParams.Add("organizationId", this.Configuration.ApiClient.ParameterToString(organizationId)); // path parameter
            // authentication (oauth2) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetOrganizationUnitMember", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OrganizationUnitMember>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (OrganizationUnitMember) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(OrganizationUnitMember)));
        }

    }
}
