/* 
 * OpenBots Server API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = OpenBots.Server.SDK.Client.SwaggerDateConverter;

namespace OpenBots.Server.SDK.Model
{
    /// <summary>
    /// Defines OperationType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum OperationType
    {
        /// <summary>
        /// Enum Add for value: Add
        /// </summary>
        [EnumMember(Value = "Add")]
        Add = 1,
        /// <summary>
        /// Enum Remove for value: Remove
        /// </summary>
        [EnumMember(Value = "Remove")]
        Remove = 2,
        /// <summary>
        /// Enum Replace for value: Replace
        /// </summary>
        [EnumMember(Value = "Replace")]
        Replace = 3,
        /// <summary>
        /// Enum Move for value: Move
        /// </summary>
        [EnumMember(Value = "Move")]
        Move = 4,
        /// <summary>
        /// Enum Copy for value: Copy
        /// </summary>
        [EnumMember(Value = "Copy")]
        Copy = 5,
        /// <summary>
        /// Enum Test for value: Test
        /// </summary>
        [EnumMember(Value = "Test")]
        Test = 6,
        /// <summary>
        /// Enum Invalid for value: Invalid
        /// </summary>
        [EnumMember(Value = "Invalid")]
        Invalid = 7    }
}
